on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: carlthome/workflows/.github/workflows/nix.yaml@main
    with:
      cachix-cache: mirpkgs
    secrets:
      cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
